name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

env:
  GO_VERSION: '1.22'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Lint
        run: go run mage.go lint
      - name: Tests
        run: go run mage.go test
      - name: Build
        run: go run mage.go build
